### ISSUE TITLE
ldi-orchestrator:20230419T081024 crashed: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#175]
**To Reproduce**

Test plan: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/020.client-pause-and-resume
Tag provided by @rorlic  for sprint 25.
[ghcr.io/informatievlaanderen/ldi-orchestrator:20230419T081024](ldi-orchestrator:20230419T081024)

- VSDS-LDES-E2E-testing: b50091609d92389b58c6c5c6030c83c77c95a467
- LDI_ORCHESTRATOR_TAG=20230419T081024

**Scenario:**
1. Follow the steps documented in https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/020.client-pause-and-resume.
2. Till execute` docker compose --env-file .env up ldio-workflow -d`

**Current result:**

ldi-orchestrator:20230419T081024 crashed: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)

```
2023-05-02 14:32:14    _       ___     ___              ___                    _                        _                       _
2023-05-02 14:32:14   | |     |   \   |_ _|     o O O  / _ \     _ _    __    | |_      ___     ___    | |_      _ _   __ _    | |_     ___      _ _
2023-05-02 14:32:14   | |__   | |) |   | |     o      | (_) |   | '_|  / _|   | ' \    / -_)   (_-<    |  _|    | '_| / _` |   |  _|   / _ \    | '_|
2023-05-02 14:32:14   |____|  |___/   |___|   TS__[O]  \___/   _|_|_   \__|_  |_||_|   \___|   /__/_   _\__|   _|_|_  \__,_|   _\__|   \___/   _|_|_
2023-05-02 14:32:14 _|"""""|_|"""""|_|"""""| {======|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|
2023-05-02 14:32:14 "`-0-0-'"`-0-0-'"`-0-0-'./o--000'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'
2023-05-02 14:32:14 
2023-05-02 14:32:14 Version 
2023-05-02 14:32:14 Powered by Spring Boot 3.0.5
2023-05-02 14:32:14 
2023-05-02 14:32:14 2023-05-02T12:32:14.482Z  INFO 1 --- [           main] b.v.i.ldes.ldio.Application              : Starting Application using Java 18-ea with PID 1 (/ldio-application.jar started by ldes in /)
2023-05-02 14:32:14 2023-05-02T12:32:14.488Z  INFO 1 --- [           main] b.v.i.ldes.ldio.Application              : No active profile set, falling back to 1 default profile: "default"
2023-05-02 14:32:22 2023-05-02T12:32:22.713Z  WARN 1 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowAutoConfiguration': Invocation of init method failed
2023-05-02 14:32:22 2023-05-02T12:32:22.739Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
2023-05-02 14:32:22 
2023-05-02 14:32:22 Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-05-02 14:32:22 2023-05-02T12:32:22.769Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
2023-05-02 14:32:22 
2023-05-02 14:32:22 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowAutoConfiguration': Invocation of init method failed
2023-05-02 14:32:22 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:196) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[ldio-console-out-jar-with-dependencies.jar:3.0.5]
2023-05-02 14:32:22 at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[ldio-console-out-jar-with-dependencies.jar:3.0.5]
2023-05-02 14:32:22 at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[ldio-console-out-jar-with-dependencies.jar:3.0.5]
2023-05-02 14:32:22 at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[ldio-console-out-jar-with-dependencies.jar:3.0.5]
2023-05-02 14:32:22 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[ldio-console-out-jar-with-dependencies.jar:3.0.5]
2023-05-02 14:32:22 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[ldio-console-out-jar-with-dependencies.jar:3.0.5]
2023-05-02 14:32:22 at be.vlaanderen.informatievlaanderen.ldes.ldio.Application.main(Application.java:9) ~[classes!/:na]
2023-05-02 14:32:22 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
2023-05-02 14:32:22 at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
2023-05-02 14:32:22 at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[ldio-application.jar:na]
2023-05-02 14:32:22 at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[ldio-application.jar:na]
2023-05-02 14:32:22 at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[ldio-application.jar:na]
2023-05-02 14:32:22 at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466) ~[ldio-application.jar:na]
2023-05-02 14:32:22 Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because the return value of "be.vlaanderen.informatievlaanderen.ldes.ldio.config.OrchestratorConfig.getPipelines()" is null
2023-05-02 14:32:22 at be.vlaanderen.informatievlaanderen.ldes.ldio.config.FlowAutoConfiguration.registerInputBeans(FlowAutoConfiguration.java:48) ~[classes!/:na]
2023-05-02 14:32:22 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
2023-05-02 14:32:22 at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
2023-05-02 14:32:22 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:425) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:369) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:193) ~[ldio-console-out-jar-with-dependencies.jar:6.0.7]
2023-05-02 14:32:22 ... 24 common frames omitted
2023-05-02 14:32:22 
```

**Comment by Yalz** [comment]
Hi Xueying,
Could you, just to double check, change this line in your compose file?
```
volumes:
      - ./ldio-workflow.config.yml:/ldio/application.yml:ro
```
with this?
```
volumes:
      - ./ldio-workflow.config.yml:/application.yml:ro
```

**Comment by xdxxxdx** [comment]
Hello @Yalz ,

Run with: 

```
volumes:
      - ./ldio-workflow.config.yml:/application.yml:ro
```
I got error:

```
2023-05-05 10:10:04 2023-05-05T08:10:04.111Z ERROR 1 --- [pool-4-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : opening db: 'database.db': Permission denied
2023-05-05 10:10:04 2023-05-05T08:10:04.117Z ERROR 1 --- [pool-4-thread-1] b.v.i.ldes.ldio.LdesClientRunner         : LdesClientRunner FAILURE
```

[error.txt](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/files/11404375/error.txt)

Thanks

**Comment by Yalz** [comment]
@xdxxxdx 
The 20230407T130529 tag unfortunately did not have the new ldio WORKDIR fix. 
For now, I advice you to use the config as written here below, but to for now use a inmemory ldes client. This will be fixed in next sprint

**Comment by xdxxxdx** [comment]
Validated on ldi-orchestrator tag: 20230508T085639
with E2E tag: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/commit/937e069594828f84154032ebb05485323626b813
