### ISSUE TITLE
Provide ARM64 docker images 

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-Linked-Data-Interactions#26]
The current docker images for ldes-workbench-nifi doesn't run on Apple Macbook with ARM64 architecture. This is because Docker for MacOS is not able to correctly emulate the amd64 binaries for apache nifi. Since it is common for developers to use MacOS with ARM CPU, it is good to have multi-architecture docker images that can support both AMD and ARM processors.

Below is a brief log showing the java IOException
```
ldes-workbench-nifi | 2022-11-15 12:08:02,607 WARN [main] org.apache.nifi.web.server.JettyServer Failed to start web server... shutting down. 
ldes-workbench-nifi | java.io.IOException: Function not implemented 
ldes-workbench-nifi | at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:62) 
ldes-workbench-nifi | at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47) 
ldes-workbench-nifi | at org.apache.nifi.nar.NarAutoLoader.start(NarAutoLoader.java:60) 
ldes-workbench-nifi | at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:800) 
ldes-workbench-nifi | at org.apache.nifi.NiFi.<init>(NiFi.java:172) 
ldes-workbench-nifi | at org.apache.nifi.NiFi.<init>(NiFi.java:83) 
ldes-workbench-nifi | at org.apache.nifi.NiFi.main(NiFi.java:332) 
ldes-workbench-nifi | 2022-11-15 12:08:02,615 INFO [Thread-0] org.apache.nifi.NiFi Application Server shutdown started ldes-workbench-nifi | 2022-11-15 12:08:02,620 INFO [Thread-0] org.apache.nifi.nar.NarAutoLoader NAR Auto-Loader stopped ldes-workbench-nifi exited with code 0
```

Related NiFi issue created for this which is unresolved: https://issues.apache.org/jira/browse/NIFI-9177

**Comment by Tomvbe** [comment]
Closed this as this has been fixed for a while now. Ruben, our test engineer has been using all the images on his mac without any issues.
