### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-Linked-Data-Interactions#386]
**Describe the bug**
Docker log file shows multiple OOM errors:
```

   _       ___     ___              ___                    _                        _                       _
  | |     |   \   |_ _|     o O O  / _ \     _ _    __    | |_      ___     ___    | |_      _ _   __ _    | |_     ___      _ _
  | |__   | |) |   | |     o      | (_) |   | '_|  / _|   | ' \    / -_)   (_-<    |  _|    | '_| / _` |   |  _|   / _ \    | '_|
  |____|  |___/   |___|   TS__[O]  \___/   _|_|_   \__|_  |_||_|   \___|   /__/_   _\__|   _|_|_  \__,_|   _\__|   \___/   _|_|_
_|"""""|_|"""""|_|"""""| {======|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|
"`-0-0-'"`-0-0-'"`-0-0-'./o--000'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'

Version 
Powered by Spring Boot 3.1.3

2023-10-30T14:44:35.192Z  INFO 1 --- [           main] b.v.i.ldes.ldio.Application              : Starting Application using Java 18-ea with PID 1 (/ldio/ldio-application.jar started by ldio in /ldio)
2023-10-30T14:44:35.194Z  INFO 1 --- [           main] b.v.i.ldes.ldio.Application              : No active profile set, falling back to 1 default profile: "default"
2023-10-30T14:44:52.571Z  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2023-10-30T14:44:54.574Z  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
2023-10-30T14:44:54.675Z  INFO 1 --- [           main] b.v.i.ldes.ldio.Application              : Started Application in 20.793 seconds (process running for 22.428)
Exception in thread "pool-5-thread-1" java.lang.OutOfMemoryError: Java heap space
        at org.apache.jena.sparql.lang.arq.ARQParserTokenManager.<init>(ARQParserTokenManager.java:5006)
        at org.apache.jena.sparql.lang.arq.ARQParser.<init>(ARQParser.java:8128)
        at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:90)
        at org.apache.jena.sparql.lang.ParserARQ.parse$(ParserARQ.java:52)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:33)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:144)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:83)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:56)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:44)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.extractor.PropertyPathExtractor.getProperties(PropertyPathExtractor.java:36)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.getDateObserved(VersionObjectCreator.java:61)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.extractMemberInfo(VersionObjectCreator.java:48)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.apply(VersionObjectCreator.java:42)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.apply(VersionObjectCreator.java:16)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl.lambda$transformLinkedData$0(ComponentExecutorImpl.java:29)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl$$Lambda$1188/0x000000080134ae40.apply(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl.lambda$transformLinkedData$1(ComponentExecutorImpl.java:29)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl$$Lambda$1187/0x000000080134ac30.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "pool-5-thread-2" java.lang.OutOfMemoryError: Java heap space
        at org.apache.jena.sparql.lang.arq.SimpleCharStream.<init>(SimpleCharStream.java:263)
        at org.apache.jena.sparql.lang.arq.SimpleCharStream.<init>(SimpleCharStream.java:270)
        at org.apache.jena.sparql.lang.arq.ARQParser.<init>(ARQParser.java:8127)
        at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:90)
        at org.apache.jena.sparql.lang.ParserARQ.parse$(ParserARQ.java:52)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:33)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:144)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:83)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:56)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:44)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.extractor.PropertyPathExtractor.getProperties(PropertyPathExtractor.java:36)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.getDateObserved(VersionObjectCreator.java:61)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.extractMemberInfo(VersionObjectCreator.java:48)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.apply(VersionObjectCreator.java:42)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.apply(VersionObjectCreator.java:16)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl.lambda$transformLinkedData$0(ComponentExecutorImpl.java:29)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl$$Lambda$1188/0x000000080134ae40.apply(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl.lambda$transformLinkedData$1(ComponentExecutorImpl.java:29)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl$$Lambda$1187/0x000000080134ac30.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "I/O dispatcher 2" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-3" java.lang.OutOfMemoryError: Java heap space
2023-10-30T14:54:10.818Z ERROR 1 --- [pool-6-thread-1] o.a.h.i.n.c.InternalHttpAsyncClient      : I/O reactor terminated abnormally

org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:359) ~[ldio-http-enricher-jar-with-dependencies.jar:na]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[ldio-http-enricher-jar-with-dependencies.jar:na]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[ldio-http-enricher-jar-with-dependencies.jar:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.OutOfMemoryError: Java heap space

Exception in thread "pool-5-thread-4" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-5" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-6" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-7" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-8" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-9" java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.orElseThrow(Optional.java:377)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.extractMemberInfo(VersionObjectCreator.java:55)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.apply(VersionObjectCreator.java:42)
        at be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator.apply(VersionObjectCreator.java:16)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl.lambda$transformLinkedData$0(ComponentExecutorImpl.java:29)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl.lambda$transformLinkedData$1(ComponentExecutorImpl.java:29)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "pool-5-thread-10" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-11" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-12" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-13" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-14" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-15" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-16" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-17" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-18" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-19" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-20" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-21" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-5-thread-22" java.lang.OutOfMemoryError: Java heap space
```

**To Reproduce**
Run the AWV fietstellussen config.

**Expected behavior**
No OOM error :wink: .

**Comment by Yalz** [comment]
@rorlic can you mention your specs ? CPU/Mem ?

**Comment by rorlic** [comment]
this was related to the async nature of the LDIO where the output was way slower than the input, building up a huge internal backlog and ultimately failing with a OOM .. this is currently fixed
