### ISSUE TITLE
LdioLdesClientConnector: LdesClientRunner FAILURE with use-relative-url: true

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#447]
- LDIO version: [ldes/ldi-orchestrator:1.12.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/new?assignees=&labels=needs+triage&projects=&template=bug_report.md&title=#)
- Add:    use-relative-url: true  after https://github.com/Informatievlaanderen/VSDS-Dataspace-Connector/blob/9f45c26e84b7067e530ff5803d60a735899b78da/e2e-test/config/ldes-server.config.yml#L9

**Scenario:**
1. Follow the step by step guide: https://github.com/Informatievlaanderen/VSDS-Dataspace-Connector/blob/main/e2e-test/README.md

**Current result:** 
 After call http://localhost:8082/client-pipeline/transfer, LdesClientRunner FAILURE
Full log:
```
2024-01-02 14:37:35    _       ___     ___              ___                    _                        _                       _
2024-01-02 14:37:35   | |     |   \   |_ _|     o O O  / _ \     _ _    __    | |_      ___     ___    | |_      _ _   __ _    | |_     ___      _ _
2024-01-02 14:37:35   | |__   | |) |   | |     o      | (_) |   | '_|  / _|   | ' \    / -_)   (_-<    |  _|    | '_| / _` |   |  _|   / _ \    | '_|
2024-01-02 14:37:35   |____|  |___/   |___|   TS__[O]  \___/   _|_|_   \__|_  |_||_|   \___|   /__/_   _\__|   _|_|_  \__,_|   _\__|   \___/   _|_|_
2024-01-02 14:37:35 _|"""""|_|"""""|_|"""""| {======|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|
2024-01-02 14:37:35 "`-0-0-'"`-0-0-'"`-0-0-'./o--000'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'
2024-01-02 14:37:35 
2024-01-02 14:37:35 Version 
2024-01-02 14:37:35 Powered by Spring Boot 3.1.3
2024-01-02 14:37:35 
2024-01-02 14:37:35 2024-01-02T13:37:35.599Z  INFO 1 --- [           main] b.v.i.ldes.ldio.Application              : Starting Application using Java 18-ea with PID 1 (/ldio/ldio-application.jar started by ldio in /ldio)
2024-01-02 14:37:35 2024-01-02T13:37:35.602Z DEBUG 1 --- [           main] b.v.i.ldes.ldio.Application              : Running with Spring Boot v3.1.3, Spring v6.0.11
2024-01-02 14:37:35 2024-01-02T13:37:35.603Z  INFO 1 --- [           main] b.v.i.ldes.ldio.Application              : No active profile set, falling back to 1 default profile: "default"
2024-01-02 14:37:37 2024-01-02T13:37:37.334Z  WARN 1 --- [           main] b.v.i.l.l.config.FlowAutoConfiguration   : No adapter configured for pipeline client-pipeline. Please verify this is a desired scenario.
2024-01-02 14:37:37 2024-01-02T13:37:37.354Z  INFO 1 --- [pool-5-thread-1] b.v.i.ldes.ldio.LdioLdesClient           : Starting LdesClientRunner run setup
2024-01-02 14:37:37 2024-01-02T13:37:37.361Z  INFO 1 --- [pool-5-thread-1] b.v.i.ldes.ldio.LdioLdesClient           : LdesClientRunner setup finished
2024-01-02 14:37:37 2024-01-02T13:37:37.755Z  WARN 1 --- [pool-6-thread-1] org.apache.sis.system                    : The “SIS_DATA” environment variable is not set.
2024-01-02 14:37:37 2024-01-02T13:37:37.828Z  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2024-01-02 14:37:37 2024-01-02T13:37:37.940Z  INFO 1 --- [pool-6-thread-1] l.c.s.StartingTreeNodeFinder             : determineStartingTreeNode for: http://consumer-connector:29291/public
2024-01-02 14:37:37 2024-01-02T13:37:37.943Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:37:38 2024-01-02T13:37:38.290Z  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8082
2024-01-02 14:37:38 2024-01-02T13:37:38.302Z  INFO 1 --- [           main] b.v.i.ldes.ldio.Application              : Started Application in 3.044 seconds (process running for 3.56)
2024-01-02 14:37:42 2024-01-02T13:37:42.948Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:37:47 2024-01-02T13:37:47.949Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:37:52 2024-01-02T13:37:52.949Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:37:57 2024-01-02T13:37:57.950Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:02 2024-01-02T13:38:02.950Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:07 2024-01-02T13:38:07.950Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:12 2024-01-02T13:38:12.951Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:17 2024-01-02T13:38:17.951Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:22 2024-01-02T13:38:22.952Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:27 2024-01-02T13:38:27.952Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:32 2024-01-02T13:38:32.280Z DEBUG 1 --- [or-http-epoll-3] b.v.i.l.ldio.LdioLdesClientConnectorApi  : POST /client-pipeline type: application/json length: 654
2024-01-02 14:38:32 2024-01-02T13:38:32.953Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:37 2024-01-02T13:38:37.953Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:42 2024-01-02T13:38:42.954Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:47 2024-01-02T13:38:47.954Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:52 2024-01-02T13:38:52.955Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:57 2024-01-02T13:38:57.955Z  INFO 1 --- [pool-6-thread-1] b.v.i.l.l.r.e.e.s.MemoryTokenService     : waiting for token..
2024-01-02 14:38:58 2024-01-02T13:38:58.794Z DEBUG 1 --- [or-http-epoll-3] b.v.i.l.ldio.LdioLdesClientConnectorApi  : POST /client-pipeline type: application/json length: 654
2024-01-02 14:39:00 2024-01-02T13:39:00.592Z DEBUG 1 --- [or-http-epoll-4] b.v.i.l.ldio.LdioLdesClientConnectorApi  : POST /client-pipeline type: application/json;charset=utf-8 length: 1223
2024-01-02 14:39:03 2024-01-02T13:39:03.044Z ERROR 1 --- [pool-5-thread-1] b.v.i.ldes.ldio.LdioLdesClient           : LdesClientRunner FAILURE
2024-01-02 14:39:03 
2024-01-02 14:39:03 ldes.client.treenodesupplier.ClientInterruptedException: Client is interrupted.
2024-01-02 14:39:03 at ldes.client.treenodesupplier.MemberSupplier.get(MemberSupplier.java:35) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
2024-01-02 14:39:03 at be.vlaanderen.informatievlaanderen.ldes.ldio.LdioLdesClient.run(LdioLdesClient.java:55) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
2024-01-02 14:39:03 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
2024-01-02 14:39:03 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
2024-01-02 14:39:03 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
2024-01-02 14:39:03 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
2024-01-02 14:39:03 at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
2024-01-02 14:39:03 Caused by: java.util.concurrent.ExecutionException: ldes.client.startingtreenode.exception.StartingNodeNotFoundException: Starting Node could not be identified from url http://consumer-connector:29291/public.
2024-01-02 14:39:03 Unable to hande response 500
2024-01-02 14:39:03 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
2024-01-02 14:39:03 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
2024-01-02 14:39:03 at ldes.client.treenodesupplier.MemberSupplier.get(MemberSupplier.java:30) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
2024-01-02 14:39:03 ... 6 common frames omitted
2024-01-02 14:39:03 Caused by: ldes.client.startingtreenode.exception.StartingNodeNotFoundException: Starting Node could not be identified from url http://consumer-connector:29291/public.
2024-01-02 14:39:03 Unable to hande response 500
2024-01-02 14:39:03 at ldes.client.startingtreenode.RedirectRequestExecutor.execute(RedirectRequestExecutor.java:41) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
2024-01-02 14:39:03 at ldes.client.startingtreenode.StartingTreeNodeFinder.determineStartingTreeNode(StartingTreeNodeFinder.java:36) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
2024-01-02 14:39:03 at ldes.client.treenodesupplier.StartingTreeNodeSupplier.getStart(StartingTreeNodeSupplier.java:21) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
2024-01-02 14:39:03 at ldes.client.treenodesupplier.TreeNodeProcessor.initializeTreeNodeRecordRepository(TreeNodeProcessor.java:91) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
2024-01-02 14:39:03 at ldes.client.treenodesupplier.TreeNodeProcessor.getMember(TreeNodeProcessor.java:75) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
2024-01-02 14:39:03 ... 4 common frames omitted
2024-01-02 14:39:03 
```

**Expected result:** 
Ldio processor LdioLdesClientConnector should be able to handle relative URLs.

**Comment by Yalz** [comment]
As can be seen by our basic connector e2e test (now moved to [here](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/034.dataspace-connector-consumer-and-provider)), the use-relative-url is simply not needed.
The client connector will take care of the rewriting.
