### ISSUE TITLE
 LDES Discoverer crashed with relative url: ldes/ldes-discoverer:2.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#526]
**Prerequisites:**
1. VSDS server configured with relative `url`, and bearb collection is published on it.
2. View `http://ldes-server:8080/bearb/timebased` is created 
```
@prefix bearb: <../../bearb/> .
@prefix ldes:  <https://w3id.org/ldes#> .
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix shacl: <http://www.w3.org/ns/shacl#> .
@prefix terms: <http://purl.org/dc/terms/> .
@prefix tree:  <https://w3id.org/tree#> .

bearb:timebased  rdf:type  tree:Node;
        tree:relation  [ rdf:type    tree:InBetweenRelation;
                         tree:node   <../../bearb/timebased?year=2015>;
                         tree:path   prov:generatedAtTime;
                         tree:value  "2015"^^<http://www.w3.org/2001/XMLSchema#gYear>
                       ] .

[ rdf:type  shacl:NodeShape ] .

<../../bearb>  rdf:type     ldes:EventStream;
        ldes:timestampPath  prov:generatedAtTime;
        ldes:versionOfPath  terms:isVersionOf;
        tree:view           bearb:timebased .

```
3.  LDES Discoverer is configured in the `docker compose file` and 

```
    ldio-discoverer:
        container_name: ldio-discoverer
        image: ldes/ldes-discoverer:2.1.0-SNAPSHOT
        command:
            - "--url=http://ldes-server:8080/bearb/timebased"
        networks:
        - ldes
        profiles:
        - delay-started
```
**Scenarios:**
1. Run docker compose up  `ldio-discoverer `

**Current result:**
 LDES Discoverer crashed with 
```
2024-03-04 17:33:41 
2024-03-04 17:33:41   .   ____          _            __ _ _
2024-03-04 17:33:41  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2024-03-04 17:33:41 ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2024-03-04 17:33:41  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2024-03-04 17:33:41   '  |____| .__|_| |_|_| |_\__, | / / / /
2024-03-04 17:33:41  =========|_|==============|___/=/_/_/_/
2024-03-04 17:33:41  :: Spring Boot ::                (v3.1.3)
2024-03-04 17:33:41 
2024-03-04 17:33:41 2024-03-04T16:33:41.294Z  INFO 1 --- [           main] b.v.i.ldes.ldi.discoverer.Application    : Starting Application using Java 17.0.10 with PID 1 (/ldes-discoverer/lib/ldes-discoverer.jar started by ldes-discoverer in /ldes-discoverer)
2024-03-04 17:33:41 2024-03-04T16:33:41.303Z  INFO 1 --- [           main] b.v.i.ldes.ldi.discoverer.Application    : No active profile set, falling back to 1 default profile: "default"
2024-03-04 17:33:43 2024-03-04T16:33:43.701Z  INFO 1 --- [           main] b.v.i.ldes.ldi.discoverer.Application    : Started Application in 3.39 seconds (process running for 4.771)
2024-03-04 17:33:43 2024-03-04T16:33:43.707Z  INFO 1 --- [           main] b.v.i.l.l.d.c.LdesDiscovererExecutor     : Running LDESDiscoverer for url http://ldes-server:8080/bearb/timebased
2024-03-04 17:33:45 2024-03-04T16:33:45.592Z  INFO 1 --- [           main] l.c.s.StartingTreeNodeRelationsFinder    : Parsing response for: http://ldes-server:8080/bearb/timebased
2024-03-04 17:33:45 2024-03-04T16:33:45.625Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
2024-03-04 17:33:45 
2024-03-04 17:33:45 Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-03-04 17:33:45 2024-03-04T16:33:45.676Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
2024-03-04 17:33:45 
2024-03-04 17:33:45 java.lang.IllegalStateException: Failed to execute CommandLineRunner
2024-03-04 17:33:45 at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-3.1.3.jar!/:3.1.3]
2024-03-04 17:33:45 at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) ~[spring-boot-3.1.3.jar!/:3.1.3]
2024-03-04 17:33:45 at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) ~[spring-boot-3.1.3.jar!/:3.1.3]
2024-03-04 17:33:45 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.3.jar!/:3.1.3]
2024-03-04 17:33:45 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.3.jar!/:3.1.3]
2024-03-04 17:33:45 at be.vlaanderen.informatievlaanderen.ldes.ldi.discoverer.Application.main(Application.java:9) ~[!/:na]
2024-03-04 17:33:45 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2024-03-04 17:33:45 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
2024-03-04 17:33:45 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2024-03-04 17:33:45 at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
2024-03-04 17:33:45 at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[ldes-discoverer.jar:na]
2024-03-04 17:33:45 at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[ldes-discoverer.jar:na]
2024-03-04 17:33:45 at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[ldes-discoverer.jar:na]
2024-03-04 17:33:45 Caused by: be.vlaanderen.informatievlaanderen.ldes.ldi.requestexecutor.exceptions.HttpRequestException: org.apache.http.client.ClientProtocolException
2024-03-04 17:33:45 at be.vlaanderen.informatievlaanderen.ldes.ldi.requestexecutor.executor.noauth.DefaultRequestExecutor.execute(DefaultRequestExecutor.java:26) ~[request-executor-2.1.0-SNAPSHOT.jar!/:na]
2024-03-04 17:33:45 at ldes.client.treenoderelationsfetcher.TreeRelationsFetcher.fetchTreeRelations(TreeRelationsFetcher.java:22) ~[tree-node-relations-fetcher-2.1.0-SNAPSHOT.jar!/:na]
2024-03-04 17:33:45 at ldes.client.treenoderelationsfetcher.LdesStructureDiscoverer.fetchRelations(LdesStructureDiscoverer.java:50) ~[tree-node-relations-fetcher-2.1.0-SNAPSHOT.jar!/:na]
2024-03-04 17:33:45 at ldes.client.treenoderelationsfetcher.LdesStructureDiscoverer.lambda$discoverLdesStructure$0(LdesStructureDiscoverer.java:33) ~[tree-node-relations-fetcher-2.1.0-SNAPSHOT.jar!/:na]
2024-03-04 17:33:45 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
2024-03-04 17:33:45 at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[na:na]
2024-03-04 17:33:45 at ldes.client.treenoderelationsfetcher.LdesStructureDiscoverer.discoverLdesStructure(LdesStructureDiscoverer.java:31) ~[tree-node-relations-fetcher-2.1.0-SNAPSHOT.jar!/:na]
2024-03-04 17:33:45 at be.vlaanderen.informatievlaanderen.ldes.ldi.discoverer.common.LdesDiscovererExecutor.run(LdesDiscovererExecutor.java:29) ~[!/:na]
2024-03-04 17:33:45 at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.3.jar!/:3.1.3]
2024-03-04 17:33:45 ... 12 common frames omitted
2024-03-04 17:33:45 Caused by: org.apache.http.client.ClientProtocolException: null
2024-03-04 17:33:45 at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187) ~[httpclient-4.5.13.jar!/:4.5.13]
2024-03-04 17:33:45 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar!/:4.5.13]
2024-03-04 17:33:45 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar!/:4.5.13]
2024-03-04 17:33:45 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar!/:4.5.13]
2024-03-04 17:33:45 at be.vlaanderen.informatievlaanderen.ldes.ldi.requestexecutor.executor.noauth.DefaultRequestExecutor.execute(DefaultRequestExecutor.java:24) ~[request-executor-2.1.0-SNAPSHOT.jar!/:na]
2024-03-04 17:33:45 ... 30 common frames omitted
2024-03-04 17:33:45 Caused by: org.apache.http.ProtocolException: Target host is not specified
2024-03-04 17:33:45 at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71) ~[httpclient-4.5.13.jar!/:4.5.13]
2024-03-04 17:33:45 at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125) ~[httpclient-4.5.13.jar!/:4.5.13]
2024-03-04 17:33:45 at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.13.jar!/:4.5.13]
2024-03-04 17:33:45 ... 34 common frames omitted
2024-03-04 17:33:45 

```

I think there should be an option to allow  LDES Discoverer work with relative `url`.

Thanks

**Comment by jobulcke** [comment]
The discoverer had by default source-format `application/n-quads`, but this format does not work with relative uris. The quick work around for this is to provide `--source-format=text/turtle`, but in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pull/572 the default source-format will be changed to `text/turtle` to support relative uris by default
