### ISSUE TITLE
SPARQL construct NiFi processor is broken when producing one-to-many messages using the graph splitting technique

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-Linked-Data-Interactions#664]
When a SPARQL Contruct processor is configured to split a linked data model using graphs, errors are thrown preventing the pipeline to continue.

**To Reproduce**
(see next comment for test setup)

0. Download the [RML adapter processor](https://s01.oss.sonatype.org/service/local/repositories/snapshots/content/be/vlaanderen/informatievlaanderen/ldes/ldi/nifi/rml-adapter-processor/2.9.0-SNAPSHOT/rml-adapter-processor-2.9.0-20240703.123646-1.nar) and the [SPARQL Construct processor](https://s01.oss.sonatype.org/service/local/repositories/snapshots/content/be/vlaanderen/informatievlaanderen/ldes/ldi/nifi/sparql-interactions-processor/2.9.0-SNAPSHOT/sparql-interactions-processor-2.9.0-20240703.123646-1.nar) in the local NiFi extensions folder

1. Start NiFi workbench:
    ```bash
    clear
    docker compose up -d --wait
    ```

2. Log on to the NiFi workbench at https://localhost:8443/nifi using the credentials found in the .env file

3. Import the pipeline (create process group & browse for the this pipeline)

4. Start the pipeline

5. Process the data:
    ```bash
    curl -X POST -H "Content-Type: text/csv" http://localhost:8080/pipeline --data-binary @./data.csv
    ```

6. Verify that the SPARQL Construct processor issues errors:
    ```log
    2024-07-11 09:21:36,928 WARN [Timer-Driven Process Thread-2] o.a.n.controller.tasks.ConnectableTask Processing halted: uncaught exception in Component [SparqlConstructProcessor[id=1e1bc70f-4f13-36fd-61c4-5dffa7f88225]]
    org.apache.nifi.processor.exception.FlowFileHandlingException: StandardFlowFileRecord[uuid=4d37a9ae-4269-434c-ba28-b76f9207db5f,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1720689654679-1, container=default, section=1], offset=1627, length=5892],offset=0,name=4d37a9ae-4269-434c-ba28-b76f9207db5f,size=5892] is not known in this session (StandardProcessSession[id=43])
            at org.apache.nifi.controller.repository.StandardProcessSession.validateRecordState(StandardProcessSession.java:3714)
            at org.apache.nifi.controller.repository.StandardProcessSession.validateRecordState(StandardProcessSession.java:3700)
            at org.apache.nifi.controller.repository.StandardProcessSession.transfer(StandardProcessSession.java:2351)
            at be.vlaanderen.informatievlaanderen.ldes.ldi.processors.services.FlowManager.sendRDFToRelation(FlowManager.java:84)
            at be.vlaanderen.informatievlaanderen.ldes.ldi.processors.services.FlowManager.sendRDFToRelation(FlowManager.java:73)
            at be.vlaanderen.informatievlaanderen.ldes.ldi.processors.SparqlConstructProcessor.onTrigger(SparqlConstructProcessor.java:61)
            at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
            at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1274)
            at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:244)
            at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:102)
            at org.apache.nifi.engine.FlowEngine$2.run(FlowEngine.java:110)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
            at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
            at java.base/java.lang.Thread.run(Thread.java:1583)
    ```

**Expected behavior**
Multiple flow files should be created and the pipeline should continue.

**Comment by rorlic** [comment]
Test setup attached: [ldio.gh#664.zip](https://github.com/user-attachments/files/16174383/ldio.gh.664.zip)
